// Problem 29
// How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?

package main

import (
	"fmt"
	"big"
)

func how_many(inf_a, sup_a, inf_b, sup_b int) int {
	seen := make(map[string]bool)
	for a := inf_a; a <= sup_a; a++ {
		a_big := big.NewInt(int64(a))
		p := big.NewInt(1)
		for b := 1; b <= sup_b; b++ {
			p.Mul(p, a_big)
			if b >= inf_b {
				seen[p.String()] = true
			}
		}
	}
	return len(seen)
}

func main() {
	const inf_a, sup_a, inf_b, sup_b = 2, 100, 2, 100
	fmt.Println(how_many(inf_a, sup_a, inf_b, sup_b))
}